/*
 * main_logic.h
 *
 *  Created on: Apr 8, 2026
 *      Author: szneqz
 */

#ifndef INC_MAIN_LOGIC_H_
#define INC_MAIN_LOGIC_H_

#include "hub75_ospi.h"
#include "nokia3310.h"
#include "gamepad.h"

enum MENU_TYPE {
	MAIN_MENU, EMOTES_MENU, GAMES_MENU, EMBLEM_MENU, MENU_TYPE_COUNT
};

enum MAIN_MENU_SELECTIONS {
	EMOTES, GAMES, EMBLEM, BACKLIGHT, GLITCH, MAIN_MENU_SELECTIONS_COUNT
};

enum EMOTES_MENU_SELECTIONS {
	STANDARD_PROTOGEN, EMOTES_MENU_SELECTIONS_COUNT
};

enum GAMES_MENU_SELECTIONS {
	GAME_LIST, SNAKE, TETRIS, GAMES_MENU_SELECTIONS_COUNT
};

enum COLOR_SELECTIONS {
	RED, GREEN, BLUE, YELLOW, CYAN, MAGENTA, WHITE, RAINBOW, COLOR_SELECTIONS_COUNT
};

void LogicLoop(void);

#endif /* INC_MAIN_LOGIC_H_ */
